Repository extreme-rock/GetARock-iOS, pull requests merged in 2023-01, with the labels that each got.

#6 [Setting] Xcode 프로젝트를 생성하고 초기 세팅을 했습니다.
  .DS_Store
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  GetARock/GetARock.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  GetARock/GetARock/Global/Base/BaseViewController.swift
  GetARock/GetARock/Global/Extension/UIColor+Extension.swift
  GetARock/GetARock/Global/Literal/ImageLiteral.swift
  GetARock/GetARock/Global/Literal/StringLiteral.swift
  GetARock/GetARock/Global/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/Contents.json
  GetARock/GetARock/Global/Supports/AppDelegate.swift
  GetARock/GetARock/Global/Supports/Info.plist
  GetARock/GetARock/Global/Supports/SceneDelegate.swift
  GetARock/GetARock/Global/UIComponent/SampleView.swift
  GetARock/GetARock/Screens/Landing/View/LandingViewController.swift
  GetARock/GetARockTests/GetARockTests.swift
  GetARock/GetARockUITests/GetARockUITests.swift
  GetARock/GetARockUITests/GetARockUITestsLaunchTests.swift
Labels: setting, 로라

#12 [Setting] CocoaPods을 설치하고 GoogleMaps를 추가합니다.
  .DS_Store
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock.xcworkspace/contents.xcworkspacedata
  GetARock/GetARock.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  GetARock/GetARock/Global/Supports/AppDelegate.swift
  GetARock/Podfile
  GetARock/Podfile.lock
Labels: setting, 로라

#17 [Add] Google Maps API KEY를 github 상에서 숨깁니다.
  .DS_Store
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Extension/Bundle+Extension.swift
  GetARock/GetARock/Global/Supports/AppDelegate.swift
  GetARock/GetARock/Global/Supports/MapsInfo.plist
Labels: API, 로라, for 뉴비

#29 [Design] Extension Color 값들을 추가합니다.
  GetARock/GetARock/Global/Extension/UIColor+Extension.swift
Labels: design, 노엘

#22 [Fix] .gitignore 적용을 위해 이전 깃 캐쉬를 삭제를 재진행하였습니다
  .DS_Store
Labels: bugfix, 노엘

#31 [Design] extension UIFont를 통해 font Type를 추가합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Extension/UIFont+Extension.swift
Labels: design, 노엘

#35 [Design] 메인 지도 뷰 UI를 구성합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Extension/Bundle+Extension.swift
  GetARock/GetARock/Global/Resource/Assets.xcassets/createEventsButton.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/createEventsButton.imageset/createEventsButton.svg
  GetARock/GetARock/Global/Resource/Assets.xcassets/currentLocationButton.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/currentLocationButton.imageset/currentLocationButton.svg
  GetARock/GetARock/Global/Resource/Assets.xcassets/myBandsButton.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/myBandsButton.imageset/myBandsButton.svg
  GetARock/GetARock/Global/Resource/Assets.xcassets/myPageButton.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/myPageButton.imageset/myPageButton.svg
  GetARock/GetARock/Global/Resource/Assets.xcassets/notificationButton.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/notificationButton.imageset/notificationButton.svg
  GetARock/GetARock/Global/Resource/Assets.xcassets/settingButton.imageset/Contents.json
  GetARock/GetARock/Global/Resource/Assets.xcassets/settingButton.imageset/settingButton.svg
  GetARock/GetARock/Screens/Landing/LandingViewController.swift
  GetARock/GetARock/Screens/Maps/MainMapViewController.swift
Labels: design, 로라, 지도

#36 [Feat] 사용자의 현재 위치를 지도 상에 표시합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Screens/Maps/MainMapViewController.swift
Labels: feat, 지도

#37 [Design] 공통 컴포넌트인 기본 TextField를 추가합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Base/BaseViewController.swift
  GetARock/GetARock/Global/Extension/UITextField+Extension.swift
  GetARock/GetARock/Global/UIComponent/BasicTextField.swift
  GetARock/GetARock/Global/Utils/TextFieldSize.swift
  GetARock/GetARock/Screens/Landing/LandingViewController.swift
Labels: design, 공통

#43 [Design] 그라데이션을 추가 하기 위해 UIView+Gradation를 제작합니다.
  GetARock/GetARock.xcodeproj/project.pbxproj
  GetARock/GetARock/Global/Extension/UIView+Gradation.swift
  GetARock/GetARock/Screens/Landing/LandingViewController.swift
Labels: design, 공통

#47 [Fix] 지도가 계속해서 현재 위치로 이동하는 것을 막습니다.
  GetARock/GetARock/Screens/Maps/MainMapViewController.swift
Labels: bugfix, 지도
